# Basic Information 
title: Matthew Jones
position: Research Associate
affiliation: University of Sheffield
affiliation_link: https://www.sheffield.ac.uk/mecheng
email: matthew.r.jones@sheffield.ac.uk

# Search Engine Optimization (SEO)
keywords: matthew jones, matthew rhys jones, matthew jones sheffield
canonical: https:/matthewrhysjones.github.io/
description: Matt is a Research Associate at the University of Sheffield. His research lies in fusing interpretability and physics within probabilstic machine learners.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com.tw/citations?user=BIC1_BIAAAAJ&hl=en
cv_link: 
github_link: https://github.com/matthewrhysjones
linkedin: https://www.linkedin.com/in/matthew-r-jones0123/
twitter: https://twitter.com/mattrjones11

# Images 
avatar: ./assets/img/profile.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: false
footnote: Website generated using minimal-light
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id:

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
